export { PropsEditor } from './react/PropsEditor.js'
export { ItemEditor } from './react/ItemEditor.js'
export { RichEditor } from './react/RichEditor.js'
export { TemplateEditor } from './react/editors/TemplateEditor.js'
export { RecordEditor } from './react/editors/RecordEditor.js'
export { TupleEditor } from './react/editors/TupleEditor.js'
export { ComboboxEditor } from './react/editors/ComboboxEditor.js'
export { CatalogEditor } from './react/editors/CatalogEditor.js'
export { FunctionCallEditor } from './react/editors/FunctionCallEditor.js'
export { recordFactories } from './react/editors/RecordEditor.js'
export { CatalogIconContext, useCatalogIcon } from './react/catalog-icon-context.js'
export type { CatalogIconRenderer } from './react/catalog-icon-context.js'
export { valuesEqual, findPreset, findFactory, literalDefinition, valueFitsType, activeCatalogIndex, defaultCall, setCallArgument } from './types/catalog.js'
export type { CatalogMatch } from './types/catalog.js'
export type { ValueCatalog, ValueCatalogGroup, ValueCatalogPreset, ValueFactory } from './types/prop-definition.js'
export { InterpolatablesContext, useInterpolatables } from './react/interpolatables-context.js'
export { ReferenceEditor, ReferenceChip, ParameterMenu } from './react/editors/ReferenceEditor.js'
export { PropRow } from './react/PropRow.js'
export type { PropRowProps } from './react/PropRow.js'
export { isComplexPropType } from './react/complex-type.js'
export { shortSyntax, typeSummary } from './react/format-syntax.js'
export type { PropsEditorProps, ItemEditorProps, EditorPlugin, SlotPath } from './react/types.js'
export type { TemplateEditorProps } from './react/editors/TemplateEditor.js'

// Re-export lightweight utilities so client code doesn't need the main entry
// (which transitively pulls in the typescript compiler via extraction code).
export { collectImports, valueToDisplayString, valueToSourceText, propertyKeyToSource, referenceToSource } from './editing/value-to-string.js'
export { materializeValue } from './materialize/materialize-value.js'
export { TemplateValueBuilder } from './types/template-value-builder.js'
export { getSelectableUnionInfo, matchUnionMember } from './types/selectable-union.js'
export { getOpenStringUnionInfo, filterSuggestions } from './types/open-string-union.js'
export type { OpenStringUnionInfo } from './types/open-string-union.js'
export { defaultValueForType } from './types/default-value.js'
export { renameRecordKey, recordKeyError, uniqueRecordKey, listElements, canRemoveTupleElement } from './types/record-entries.js'
export { slotDefinition } from './types/prop-type.js'
export type { SelectableUnionInfo } from './types/selectable-union.js'
export { interpolatablesFromDefinitions, parseInterpolationPath, resolveInterpolatable, interpolationSuggestions, collapseTemplateValue, interpolatablePaths } from './editing/interpolation.js'
